### ISSUE TITLE
Shinken app redirects to login page when logged in

### ISSUE THREAD

**Issue by arthurzenika** [YunoHost-Apps/shinken_ynh#2]
Thanks for working on this app for shinken, this might prove usefull to us ! 

Right now, after an install in the /shinken/ URL (is this an option ? or it only works on a subdomain with the "/" URL ?)  I get redirected to /user/login (with a 303 which is surprising). 

Happy to help debug this. Will try an installation on a subdomain.

**Comment by arthurzenika** [comment]
same same with "/" on a subdomain

**Comment by liberodark** [comment]
yes is use one domain now no sub
